version: '3.8'
services:
  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./artifacts:/artifacts
    command: mlflow ui --backend-store-uri /mlruns --default-artifact-root /artifacts --host 0.0.0.0 --port 5000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    volumes:
      - ./src:/app/src
    environment:
      - PORT=5001

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/app
networks:
  app-network:
    driver: bridge
